branch-defaults:
  dev:
    environment: teset-dev
environment-defaults:
  teset-dev2:
    branch: null
    repository: null
global:
  application_name: teset
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.5.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
